import {createPlayer, createVehicle, RARITY_META, UpgradeType, VehicleStatus} from './domain/models.js';
import {PlayerRepository} from './storage/player-repository.js';
import {RarityService} from './services/rarity-service.js';
import {EconomyService} from './services/economy-service.js';
import {ExperienceService} from './services/experience-service.js';
import {GarageService} from './services/garage-service.js';
import {VehicleService} from './services/vehicle-service.js';
import {MarketService} from './services/market-service.js';
import {TheftService} from './services/theft-service.js';
import {StakeService} from './services/stake-service.js';
import {FallbackVehicleRecognitionService, ImagePrivacyService, LicensePlateDetectionService} from './recognition/services.js';
import {RaceEngine} from './game/race-engine.js';
import {ChaseEngine} from './game/chase-engine.js';
import {RaceNetworkService, TransactionCoordinator} from './networking/race-network-service.js';
import {QuestService} from './services/quest-service.js';
import {VEHICLE_CATALOG, CAR_COLORS, RACE_MAPS} from './data/vehicle-catalog.js';

const repo = new PlayerRepository();
const services = {economy:new EconomyService(), xp:new ExperienceService(), garage:new GarageService(), vehicle:new VehicleService(), market:new MarketService(), theft:new TheftService(), stake:new StakeService(), rarity:new RarityService(), recognition:new FallbackVehicleRecognitionService(), privacy:new ImagePrivacyService(new LicensePlateDetectionService()), race:new RaceEngine(), chase:new ChaseEngine(), network:new RaceNetworkService(), transactions:new TransactionCoordinator(), quests:new QuestService()};
let player = repo.load(createPlayer());
let screen = 'home', selectedId = null, photo = null, candidate = null, toast = '', chaseState = null, trade = null, selectedMapId = 'city-dry';
const app = document.querySelector('#app');
const money = (value) => new Intl.NumberFormat('ru-RU', {style:'currency',currency:'USD',maximumFractionDigits:0}).format(value);
const selected = () => player.vehicles.find((vehicle) => vehicle.id === selectedId);
const update = (next, message = 'Готово') => { player = next; repo.save(player); toast = message; render(); };
const run = (operation) => { try { update(operation()); } catch (error) { toast = error.message; render(); } };
const meta = (vehicle) => RARITY_META[vehicle.rarity] || RARITY_META.COMMON;

function carCard(vehicle) {
  const rarity = meta(vehicle);
  return `<button class="car-card" data-car="${vehicle.id}" style="--car:${vehicle.color}"><span class="rarity" style="color:${rarity.color}">${rarity.label}</span><div class="car-shape"></div><b>${vehicle.brand} ${vehicle.model}</b><small>${vehicle.generation} · ${vehicle.bodyType}</small><footer>⚡ ${vehicle.speed} · ${money(vehicle.currentValue)} ${vehicle.damage ? `· ⚠ ${vehicle.damage}%` : ''}</footer></button>`;
}
function pageHeader(kicker, title, action = '') { return `<header class="page-header"><div><p class="eyebrow">${kicker}</p><h2>${title}</h2></div>${action}</header>`; }
function empty(text, action = 'camera') { return `<div class="empty"><p>${text}</p><button class="primary" data-nav="${action}">Продолжить</button></div>`; }
function navigation() { return `<nav>${[['home','⌂','Главная'],['collection','▦','Коллекция'],['garage','▣','Гараж'],['race-select','⚑','Гонки'],['profile','◉','Профиль']].map(([key,icon,label]) => `<button data-nav="${key}" class="${screen===key?'active':''}"><i>${icon}</i>${label}</button>`).join('')}</nav>`; }

function home() { return `<section class="hero"><p class="eyebrow">ОБИТЕЛЬ СКОРОСТИ</p><h1>Найди. <em>Собери.</em><br>Верни своё.</h1><p>Фотографируйте реальные автомобили, прокачивайте карточки и соревнуйтесь за коллекцию.</p><button class="primary" data-nav="camera">⌁ Сканировать автомобиль</button><div class="quick-actions"><button data-nav="market">Рынок</button><button data-nav="training">Тренировка</button><button data-nav="quests">Задания</button><button data-nav="bluetooth">Bluetooth</button><button data-nav="notifications">События ${player.notifications.filter(n=>!n.read).length ? '•' : ''}</button></div></section><section class="stats"><div><b>${player.vehicles.length}</b> карточек</div><div><b>${player.garageSlots}</b> мест</div><div><b>${player.level}</b> уровень</div></section><h2>Коллекция</h2><div class="grid">${player.vehicles.slice(-2).map(carCard).join('') || empty('Первая карточка ждёт вашу камеру.')}</div>`; }
function camera() { return `<section class="panel center">${pageHeader('КАМЕРА','Сканирование автомобиля')}<div class="viewfinder">${photo ? `<img src="${photo}" alt="Снятый автомобиль">` : '<span>Наведите камеру<br>на автомобиль</span>'}</div><input id="photo-input" type="file" accept="image/*" capture="environment" hidden><button class="primary" id="capture">◉ Сделать фото</button>${photo ? '<button class="secondary" id="recognize">Распознать и скрыть номер</button>' : ''}<small>До сохранения запускается privacy pipeline. Номер автомобиля не сохраняется в карточке.</small></section>`; }
function recognitionResult() { const brands=[...new Set(VEHICLE_CATALOG.map(item=>item.brand))]; return `<section class="panel">${photo ? `<img class="result-photo" src="${photo}" alt="Обработанная фотография">` : ''}${pageHeader('РЕЗУЛЬТАТ РАСПОЗНАВАНИЯ',`${candidate.brand} ${candidate.model}`)}<p class="hint">Проверьте распознавание перед выпуском карточки.</p><div class="recognition-form"><label>Марка<select id="vehicle-brand">${brands.map(brand=>`<option ${brand===candidate.brand?'selected':''}>${brand}</option>`).join('')}</select></label><label>Модель<select id="vehicle-model">${VEHICLE_CATALOG.map(item=>`<option value="${item.brand}|${item.model}" ${item.brand===candidate.brand&&item.model===candidate.model?'selected':''}>${item.brand} ${item.model}</option>`).join('')}</select></label><label>Кузов<select id="vehicle-body">${['sedan','hatchback','coupe','convertible','wagon','suv','crossover','pickup','van','supercar','hypercar','motorcycle'].map(type=>`<option ${type===candidate.bodyType?'selected':''}>${type}</option>`).join('')}</select></label><label>Цвет<select id="vehicle-color">${CAR_COLORS.map(color=>`<option value="${color}" ${color===candidate.color?'selected':''}>${color}</option>`).join('')}</select></label></div><div class="stat-row"><span>SPEED<b>${candidate.speed}</b></span><span>HANDLING<b>${candidate.handling}</b></span><span>DURABILITY<b>${candidate.durability}</b></span></div><p class="hint">Номер не сохраняется: в карточке есть только обработанное фото.</p><button id="confirm-discovery" class="primary">Создать карточку</button></section>`; }
function collection() { return `<section>${pageHeader('КОЛЛЕКЦИЯ',`${player.vehicles.length} автомобилей`,'<button class="round" data-nav="camera">＋</button>')}<div class="filters"><button>Все</button><button>Редкость</button><button>Стоимость</button></div><div class="grid">${player.vehicles.map(carCard).join('') || empty('Сканируйте автомобиль, чтобы начать коллекцию.')}</div></section>`; }
function garage() { const parked = player.vehicles.filter(v=>v.garageSlot!==null).length; return `<section>${pageHeader('ГАРАЖ',`${parked}/${player.garageSlots} мест занято`,'<button class="round" id="buy-slot">＋</button>')}<p class="hint">Машины в гараже не могут быть угнаны.</p><div class="garage-grid">${Array.from({length:player.garageSlots},(_,slot)=>{const vehicle=player.vehicles.find(v=>v.garageSlot===slot);return vehicle ? carCard(vehicle) : `<div class="empty-slot">МЕСТО ${slot+1}</div>`;}).join('')}</div><button class="secondary" id="buy-slot-bottom">Новое место · ${money(services.garage.slotsCost(player))}</button></section>`; }
function detail() { const vehicle=selected(); if(!vehicle) return collection(); return `<section><button class="back" data-nav="collection">← Коллекция</button>${carCard(vehicle)}<h2>${vehicle.brand} ${vehicle.model}</h2><p>${meta(vehicle).label} · ${vehicle.status} · Уровень ${vehicle.level}</p><div class="stat-row"><span>⚡ ${vehicle.speed}/${vehicle.maxSpeed}</span><span>◌ ${vehicle.handling}/${vehicle.maxHandling}</span><span>⬡ ${vehicle.durability}/${vehicle.maxDurability}</span></div><div class="damage"><i style="width:${vehicle.damage}%"></i></div><small>Повреждения: ${vehicle.damage}%</small><div class="actions"><button id="toggle-garage">${vehicle.garageSlot===null?'Поставить в гараж':'Снять из гаража'}</button><button data-nav="upgrade">Прокачка</button><button data-nav="repair">Ремонт</button><button data-nav="race-select">Гонка</button></div>${vehicle.status===VehicleStatus.OUTSIDE?'<button class="danger" id="risk-theft">Проверить риск угона</button>':''}${vehicle.status===VehicleStatus.STOLEN?'<button class="primary" data-nav="chase">Начать погоню</button>':''}</section>`; }
function upgrade() { const vehicle=selected(); return `<section>${pageHeader('УЛУЧШЕНИЕ',`${vehicle.brand} ${vehicle.model}`)}<p class="hint">У каждого автомобиля есть индивидуальный предел. Цена растёт с уровнем.</p><div class="upgrade-list">${Object.values(UpgradeType).map(type=>`<button data-upgrade="${type}"><b>${type}</b><span>${type==='ENGINE'?'Скорость':type==='HANDLING'?'Манёвренность':'Прочность'}</span><em>${money(services.vehicle.upgradeCost(vehicle,type))}</em></button>`).join('')}</div></section>`; }
function repair() { const vehicle=selected(); return `<section class="panel">${pageHeader('РЕМОНТ',`${vehicle.brand} ${vehicle.model}`)}<div class="damage large"><i style="width:${vehicle.damage}%"></i></div><h3>${vehicle.damage}% повреждений</h3><p>Цена ремонта зависит от стоимости автомобиля и степени повреждений: 25% стоимости восстановления.</p><button class="primary" id="confirm-repair">Восстановить · ${money(services.vehicle.repairCost(vehicle))}</button></section>`; }
function market() { const cards=player.vehicles.map(v=>`<div class="market-row"><span>${v.brand} ${v.model}<small>Продажа: 50% current value</small></span><b>${money(services.market.salePrice(v))}</b><button data-sell="${v.id}">Продать</button></div>`).join('') || '<p class="empty">Нет машин для продажи.</p>'; const listings=services.market.listings().map(v=>`<div class="market-row"><span>${v.brand} ${v.model}<small>${meta(v).label}</small></span><b>${money(v.currentValue)}</b><button data-buy="${v.id}">Купить</button></div>`).join(''); return `<section>${pageHeader('Б/У РЫНОК','Продажа и покупка')}<h3>Ваши карточки</h3>${cards}<h3>Предложения дня</h3>${listings}</section>`; }
function raceSelect() { const available=player.vehicles.filter(v=>!v.lockedBy&&v.status!==VehicleStatus.STOLEN); return `<section>${pageHeader('ГОНКИ','Выберите режим')}<div class="mode-grid"><button data-nav="bot-race"><b>🤖 Гонка с ботом</b><span>Награды, XP и повреждения.</span></button><button data-nav="bluetooth"><b>⌁ Bluetooth гонка</b><span>Поиск игроков рядом.</span></button><button data-nav="stake"><b>⚑ Гонка со ставкой</b><span>Обе стороны подтверждают машины.</span></button></div><h3>Доступные автомобили</h3><div class="grid">${available.map(carCard).join('')||empty('Нужна доступная машина.', 'camera')}</div></section>`; }
function botRace() { const vehicle=selected() || player.vehicles.find(v=>!v.lockedBy); if(!vehicle) return raceSelect(); selectedId=vehicle.id; const map=RACE_MAPS.find(item=>item.id===selectedMapId); return `<section class="race">${pageHeader('ГОНКА С БОТОМ',`${vehicle.brand} ${vehicle.model}`)}<div class="map-chip">${map.name} · ${map.weather} · препятствий: ${map.obstacles}</div><div class="track ${map.weather==='Дождь'?'wet-track':''}"><div class="racecar you" style="--car:${vehicle.color}"></div><div class="racecar bot"></div><i></i><i></i><i></i></div><div class="race-controls"><button data-steer="-1">←</button><button id="run-race">ACCELERATE</button><button data-steer="1">→</button></div><p class="hint">Карта влияет на манёвренность и риск столкновения. Выберите карту в тренировочном пространстве.</p></section>`; }
function bluetooth() { return `<section>${pageHeader('BLUETOOTH','Игроки рядом')}<div class="panel"><h3>Офлайн P2P-порт</h3><p>Транспорт изолирован от игровой логики. Для реальной игры нужен Bluetooth/WebRTC adapter и серверная валидация.</p><button class="primary" id="search-players">Искать игроков</button><div id="players-result" class="hint">Поиск ещё не запускался.</div></div><div class="actions"><button data-nav="trade">Обмен карточками</button><button data-nav="stake">Stake Race</button></div></section>`; }
function tradeView() { const vehicle=selected() || player.vehicles.find(v=>!v.lockedBy); return `<section>${pageHeader('ОБМЕН','Двустороннее подтверждение')}<div class="panel"><p>Вы предлагаете: <b>${vehicle ? `${vehicle.brand} ${vehicle.model}` : 'нет карточки'}</b></p><p>Игрок B предлагает: <b>BMW M3 Competition</b></p><p class="hint">У сделки есть transaction ID, таймаут и duplicate protection. Карточка передаётся только после двух подтверждений.</p><button class="primary" id="start-trade" ${vehicle?'':'disabled'}>${trade?'Подтвердить сделку':'Создать предложение'}</button>${trade?'<button class="secondary" id="remote-confirm">Симулировать подтверждение игрока B</button>':''}</div></section>`; }
function stake() { const vehicle=selected() || player.vehicles.find(v=>!v.lockedBy); return `<section>${pageHeader('STAKE RACE','Поставьте машину на кон')}<div class="panel"><p>Ваша ставка: <b>${vehicle?`${vehicle.brand} ${vehicle.model}`:'нет доступной машины'}</b></p><p>Соперник: <b>BMW M3 Competition</b></p><p class="hint">Заблокированную карточку нельзя использовать в другой ставке или сделке.</p><button class="primary" id="start-stake" ${vehicle?'':'disabled'}>Зафиксировать ставку</button>${player.activeStake?'<button class="secondary" id="confirm-stake">Подтвердить обе стороны и начать</button>':''}</div></section>`; }
function chase() { const stolen=player.vehicles.find(v=>v.status===VehicleStatus.STOLEN||v.status===VehicleStatus.IN_CHASE); if(!stolen) return `<section>${pageHeader('ПОГОНЯ','Нет активной погони')}<p class="empty">При угоне появится десятиминутное окно преследования.</p></section>`; if(!chaseState) chaseState={lane:1,distance:100,damage:0,ticks:0,playerSpeed:stolen.speed,targetSpeed:110,obstacleLane:0,won:false,failed:false}; return `<section class="race">${pageHeader('ПОГОНЯ',`Верните ${stolen.brand} ${stolen.model}`)}<div class="chase-road"><div class="chase-target">🚘</div><div class="chase-player" style="left:${20+chaseState.lane*30}%">🚗</div><div class="obstacle" style="left:${20+chaseState.obstacleLane*30}%">▣</div></div><p>Дистанция: <b>${chaseState.distance} м</b> · Повреждения: <b>${chaseState.damage}%</b></p><div class="race-controls"><button id="chase-left">←</button><button id="chase-boost">BOOST</button><button id="chase-right">→</button></div></section>`; }
function quests() { const quests=services.quests.definitions(); return `<section>${pageHeader('ЗАДАНИЯ','Ежедневный прогресс')}<div class="quest-list">${quests.map(quest=>{const progress=services.quests.progress(player,quest.metric);const ready=progress>=quest.target;const claimed=(player.claimedQuests??[]).includes(quest.id);return `<article><b>${quest.title}</b><p>${quest.description}</p><div class="damage"><i style="width:${Math.min(100,progress/quest.target*100)}%"></i></div><small>${progress}/${quest.target} · ${money(quest.reward.money)} + ${quest.reward.xp} XP</small><button data-quest="${quest.id}" ${!ready||claimed?'disabled':''}>${claimed?'Получено':ready?'Забрать':'В процессе'}</button></article>`;}).join('')}</div></section>`; }
function training() { const vehicle=selected()||player.vehicles.find(v=>!v.lockedBy); return `<section>${pageHeader('ТРЕНИРОВОЧНОЕ ПРОСТРАНСТВО','Карты и погодные условия')}<p class="hint">Тренировка не ставит машину на кон, но использует дорожные условия и физику гонки.</p><div class="map-list">${RACE_MAPS.map(map=>`<button data-map="${map.id}" class="${map.id===selectedMapId?'selected-map':''}"><b>${map.name}</b><span>${map.weather} · ${map.surface} · препятствий: ${map.obstacles}</span></button>`).join('')}</div><p>Выбранный автомобиль: <b>${vehicle?`${vehicle.brand} ${vehicle.model}`:'нет'}</b></p><button class="primary" id="run-training" ${vehicle?'':'disabled'}>Начать заезд</button></section>`; }
function notifications() { return `<section>${pageHeader('УВЕДОМЛЕНИЯ','События')}<div class="notification-list">${player.notifications.map(n=>`<article><b>${n.title||n.type}</b><p>${n.body||'Автомобиль угнан: срочно начните погоню.'}</p>${n.type==='THEFT'?'<button data-nav="chase">Открыть погоню</button>':''}</article>`).join('') || '<p class="empty">Новых событий нет.</p>'}</div><button id="read-notifications" class="secondary">Пометить все прочитанными</button></section>`; }
function profile() { return `<section class="panel">${pageHeader('ПРОФИЛЬ',`Гонщик · уровень ${player.level}`)}<div class="xp"><i style="width:${Math.min(100,player.experience/services.xp.requiredForLevel(player.level)*100)}%"></i></div><p>${player.experience} / ${services.xp.requiredForLevel(player.level)} XP</p><h2>${money(player.balance)}</h2><div class="actions"><button data-nav="notifications">Уведомления</button><button data-nav="settings">Настройки</button><button data-nav="market">Рынок</button></div></section>`; }
function settings() { return `<section>${pageHeader('НАСТРОЙКИ','Игра и данные')}<div class="setting"><span>Вибрация</span><button id="toggle-haptics">${player.settings?.haptics?'Включена':'Выключена'}</button></div><div class="setting"><span>Offline-first режим</span><b>Активен</b></div><div class="setting"><span>Локальное сохранение</span><b>localStorage</b></div></section>`; }
function content() { return ({home,camera,result:recognitionResult,collection,garage,detail,upgrade,repair,market,'race-select':raceSelect,'bot-race':botRace,bluetooth,trade:tradeView,stake,chase,quests,training,notifications,profile,settings}[screen] || home)(); }
function render() { app.innerHTML=`<main><div class="top"><strong>◈ SPEED HAVEN</strong><button data-nav="profile">${money(player.balance)}</button></div>${toast?`<div class="toast">${toast}</div>`:''}${content()}</main>${navigation()}`; bind(); }
function setScreen(next) { screen=next; toast=''; render(); }
function bind() {
  document.querySelectorAll('[data-nav]').forEach(button=>button.onclick=()=>setScreen(button.dataset.nav));
  document.querySelectorAll('[data-car]').forEach(button=>button.onclick=()=>{selectedId=button.dataset.car;setScreen('detail');});
  const input=document.querySelector('#photo-input'); document.querySelector('#capture')?.addEventListener('click',()=>input.click());
  input?.addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{photo=reader.result;render();};reader.readAsDataURL(file);});
  document.querySelector('#recognize')?.addEventListener('click',async()=>{try{photo=(await services.privacy.sanitize(photo)).photo;candidate=await services.recognition.recognize(photo);setScreen('result');}catch(error){toast=error.message;render();}});
  document.querySelector('#vehicle-brand')?.addEventListener('change',(event)=>{const models=VEHICLE_CATALOG.filter(item=>item.brand===event.target.value);const select=document.querySelector('#vehicle-model');select.innerHTML=models.map(item=>`<option value="${item.brand}|${item.model}">${item.brand} ${item.model}</option>`).join('');});
  document.querySelector('#confirm-discovery')?.addEventListener('click',()=>run(()=>{const selectedModel=document.querySelector('#vehicle-model').value.split('|');const base=VEHICLE_CATALOG.find(item=>item.brand===selectedModel[0]&&item.model===selectedModel[1]);if(!base||base.brand!==document.querySelector('#vehicle-brand').value) throw new Error('Выберите модель для выбранной марки');const corrected={...base,bodyType:document.querySelector('#vehicle-body').value,color:document.querySelector('#vehicle-color').value};const rarity=services.rarity.calculate(corrected);const vehicle=createVehicle({...corrected,rarity,photo});let next={...player,vehicles:[...player.vehicles,vehicle]};next=services.economy.credit(next,Math.round(vehicle.baseValue*.03),'discovery');next=services.quests.record(next,'discoveries');screen='collection';return services.xp.grant(next,90+Object.keys(RARITY_META).indexOf(rarity)*30,'discovery');}));
  ['buy-slot','buy-slot-bottom'].forEach(id=>document.querySelector(`#${id}`)?.addEventListener('click',()=>run(()=>services.garage.buySlot(player,services.economy))));
  document.querySelector('#toggle-garage')?.addEventListener('click',()=>run(()=>selected().garageSlot===null?services.quests.record(services.garage.park(player,selectedId),'parked'):services.garage.unpark(player,selectedId)));
  document.querySelector('#risk-theft')?.addEventListener('click',()=>run(()=>{const next=services.theft.attempt(player,selectedId,0.05);if(next===player)throw new Error('Угон не произошёл: действует защита или cooldown');return next;}));
  document.querySelectorAll('[data-upgrade]').forEach(button=>button.onclick=()=>run(()=>services.vehicle.upgrade(player,selectedId,button.dataset.upgrade,services.economy)));
  document.querySelector('#confirm-repair')?.addEventListener('click',()=>run(()=>services.vehicle.repair(player,selectedId,services.economy)));
  document.querySelectorAll('[data-sell]').forEach(button=>button.onclick=()=>run(()=>services.market.sell(player,button.dataset.sell,services.economy)));
  document.querySelectorAll('[data-buy]').forEach(button=>button.onclick=()=>run(()=>services.market.buy(player,services.market.listings().find(item=>item.id===button.dataset.buy),createVehicle,services.economy)));
  document.querySelector('#run-race')?.addEventListener('click',()=>run(()=>{const v=selected();const map=RACE_MAPS.find(item=>item.id===selectedMapId);const racer={...v,handling:Math.max(1,v.handling+map.handlingModifier)};const r=services.race.simulate(racer,{speed:115,handling:65,damage:0},{accelerate:1,steer:map.obstacles/10});let next={...player,vehicles:player.vehicles.map(item=>item.id===v.id?services.vehicle.applyCollision(item,r.damage):item)};next=services.economy.credit(next,r.reward,r.won?'race_win':'race_finish');next=services.quests.record(next,'races');return services.xp.grant(next,r.won?80:25,'race');}));
  document.querySelector('#search-players')?.addEventListener('click',()=>{document.querySelector('#players-result').textContent='Bluetooth adapter не подключён. Локальный режим остаётся доступен.';});
  document.querySelector('#start-trade')?.addEventListener('click',()=>{const v=selected()||player.vehicles.find(x=>!x.lockedBy);trade=services.transactions.create('TRADE',v.id,'remote-bmw');toast=`Сделка ${trade.id.slice(0,8)} создана`;render();});
  document.querySelector('#remote-confirm')?.addEventListener('click',()=>{trade=services.transactions.confirm(services.transactions.confirm(trade,'A'),'B');toast='Обе стороны подтвердили сделку. Ожидается защищённый P2P transfer.';render();});
  document.querySelector('#start-stake')?.addEventListener('click',()=>run(()=>{const v=selected()||player.vehicles.find(x=>!x.lockedBy);const result=services.stake.create(player,v.id,'remote-bmw');player={...result.player,activeStake:result.stake};return player;}));
  document.querySelector('#confirm-stake')?.addEventListener('click',()=>run(()=>{let stake=services.stake.confirm(player.activeStake,'LOCAL');stake=services.stake.confirm(stake,'REMOTE');return {...player,activeStake:stake};}));
  document.querySelectorAll('[data-quest]').forEach(button=>button.onclick=()=>run(()=>services.quests.claim(player,button.dataset.quest,services.economy,services.xp)));
  document.querySelectorAll('[data-map]').forEach(button=>button.onclick=()=>{selectedMapId=button.dataset.map;render();});
  document.querySelector('#run-training')?.addEventListener('click',()=>run(()=>{const vehicle=selected()||player.vehicles.find(v=>!v.lockedBy);const map=RACE_MAPS.find(item=>item.id===selectedMapId);const result=services.race.simulate({...vehicle,handling:Math.max(1,vehicle.handling+map.handlingModifier)},{speed:105,handling:55,damage:0},{accelerate:1,steer:map.obstacles/10});let next={...player,vehicles:player.vehicles.map(item=>item.id===vehicle.id?services.vehicle.applyCollision(item,result.damage):item)};return services.xp.grant(next,35,'training');}));
  document.querySelector('#read-notifications')?.addEventListener('click',()=>run(()=>({...player,notifications:player.notifications.map(n=>({...n,read:true}))})));
  document.querySelector('#toggle-haptics')?.addEventListener('click',()=>run(()=>({...player,settings:{...player.settings,haptics:!player.settings?.haptics}})));
  [['chase-left',{left:true}],['chase-right',{right:true}],['chase-boost',{boost:true}]].forEach(([id,inputState])=>document.querySelector(`#${id}`)?.addEventListener('click',()=>{chaseState=services.chase.step(chaseState,inputState);if(chaseState.won||chaseState.failed){const stolen=player.vehicles.find(v=>v.status===VehicleStatus.STOLEN||v.status===VehicleStatus.IN_CHASE);player=services.theft.resolveChase(player,stolen.id,chaseState.won,services.economy,services.xp);repo.save(player);toast=chaseState.won?'Погоня успешна: автомобиль возвращён!':'Погоня не удалась';chaseState=null;screen='home';}render();}));
}
render();
