import {createPlayer,createVehicle,RARITY_META,UpgradeType} from './domain/models.js';
import {PlayerRepository} from './storage/player-repository.js';
import {RarityService} from './services/rarity-service.js'; import {EconomyService} from './services/economy-service.js'; import {ExperienceService} from './services/experience-service.js'; import {GarageService} from './services/garage-service.js'; import {VehicleService} from './services/vehicle-service.js'; import {MarketService} from './services/market-service.js'; import {FallbackVehicleRecognitionService,ImagePrivacyService,LicensePlateDetectionService} from './recognition/services.js'; import {RaceEngine} from './game/race-engine.js';
const repo=new PlayerRepository(), economy=new EconomyService(), xp=new ExperienceService(), garage=new GarageService(), vehicles=new VehicleService(), market=new MarketService(), rarity=new RarityService(), recognition=new FallbackVehicleRecognitionService(), privacy=new ImagePrivacyService(new LicensePlateDetectionService()), race=new RaceEngine();
let player=repo.load(createPlayer()), screen='home', selectedId=null, photo=null, recognized=null, message='';
const app=document.querySelector('#app');
const save=()=>{repo.save(player); render();}; const selected=()=>player.vehicles.find(v=>v.id===selectedId); const money=n=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
function action(fn){try{player=fn();message='Готово';save();}catch(e){message=e.message;render();}}
function card(v){const meta=RARITY_META[v.rarity];return `<button class="car-card" data-car="${v.id}" style="--car:${v.color}"><span class="rarity" style="color:${meta.color}">${meta.label}</span><div class="car-shape"></div><b>${v.brand} ${v.model}</b><small>${v.bodyType} · ${v.speed} SPEED</small><footer>${money(v.currentValue)} ${v.damage?`· ⚠ ${v.damage}%`:''}</footer></button>`;}
function nav(){return `<nav>${[['home','⌂','Главная'],['collection','▦','Коллекция'],['garage','▣','Гараж'],['market','＄','Рынок'],['profile','◉','Профиль']].map(([s,i,l])=>`<button data-nav="${s}" class="${screen===s?'active':''}"><i>${i}</i>${l}</button>`).join('')}</nav>`;}
function view(){const s=selected(); if(screen==='home')return `<section class="hero"><p class="eyebrow">ОБИТЕЛЬ СКОРОСТИ</p><h1>Найди. <em>Собери.</em><br/>Победи.</h1><p>Фотографируй реальные автомобили и пополняй свою коллекцию.</p><button class="primary" data-nav="camera">⌁ Сканировать автомобиль</button></section><section class="stats"><div><b>${player.vehicles.length}</b> карточек</div><div><b>${player.garageSlots}</b> мест</div><div><b>${player.level}</b> уровень</div></section><h2>Последние находки</h2><div class="grid">${player.vehicles.slice(-2).map(card).join('')||'<p class="empty">Коллекция ждёт первую находку.</p>'}</div>`;
if(screen==='camera')return `<section class="panel center"><p class="eyebrow">КАМЕРА</p><h2>Сканирование автомобиля</h2><div class="viewfinder">${photo?`<img src="${photo}" alt="снятый автомобиль">`:'<span>Наведите камеру<br/>на автомобиль</span>'}</div><input id="photo-input" type="file" accept="image/*" capture="environment" hidden><button class="primary" id="capture">◉ Сделать фото</button>${photo?'<button class="secondary" id="recognize">Распознать безопасно</button>':''}<small>Номерные знаки маскируются до сохранения. Номер никогда не хранится.</small></section>`;
if(screen==='result')return `<section class="panel">${photo?`<img class="result-photo" src="${photo}" alt="обработанная фотография">`:''}<p class="eyebrow">РЕЗУЛЬТАТ РАСПОЗНАВАНИЯ</p><h2>${recognized.brand} ${recognized.model}</h2><p>${recognized.generation} · ${recognized.bodyType} · ${money(recognized.baseValue)}</p><div class="stat-row"><span>SPEED <b>${recognized.speed}</b></span><span>HANDLING <b>${recognized.handling}</b></span><span>DURABILITY <b>${recognized.durability}</b></span></div><button class="primary" id="confirm">Добавить в коллекцию</button></section>`;
if(screen==='collection')return `<section><header><div><p class="eyebrow">КОЛЛЕКЦИЯ</p><h2>${player.vehicles.length} автомобилей</h2></div><button class="round" data-nav="camera">＋</button></header><div class="filters"><button>Все</button><button>По редкости</button><button>По цене</button></div><div class="grid">${player.vehicles.map(card).join('')||'<p class="empty">Сканируйте автомобиль, чтобы создать первую карточку.</p>'}</div></section>`;
if(screen==='garage')return `<section><header><div><p class="eyebrow">ГАРАЖ</p><h2>${player.vehicles.filter(v=>v.garageSlot!==null).length}/${player.garageSlots} мест занято</h2></div><button class="round" id="slot">＋</button></header><p class="hint">Защищённые от угона автомобили</p><div class="garage-grid">${Array.from({length:player.garageSlots},(_,i)=>{const v=player.vehicles.find(x=>x.garageSlot===i);return v?card(v):`<div class="empty-slot">МЕСТО ${i+1}</div>`}).join('')}</div><p>Следующее место: ${money(garage.slotsCost(player))}</p></section>`;
if(screen==='market')return `<section><p class="eyebrow">Б/У РЫНОК</p><h2>Продажа автомобилей</h2><p class="hint">Базовая цена продажи — 50% текущей стоимости.</p><div class="list">${player.vehicles.map(v=>`<div>${v.brand} ${v.model}<b>${money(market.salePrice(v))}</b><button data-sell="${v.id}">Продать</button></div>`).join('')||'<p class="empty">Нет автомобилей для продажи.</p>'}</div></section>`;
if(screen==='detail'&&s)return `<section><button class="back" data-nav="collection">← Коллекция</button>${card(s)}<h2>${s.brand} ${s.model}</h2><div class="stat-row"><span>⚡ ${s.speed}/${s.maxSpeed}</span><span>◌ ${s.handling}/${s.maxHandling}</span><span>⬡ ${s.durability}/${s.maxDurability}</span></div><p>Повреждения: <b>${s.damage}%</b> · Статус: ${s.status}</p><div class="actions"><button id="park">${s.garageSlot===null?'Поставить в гараж':'Снять с гаража'}</button><button id="race">Гонка с ботом</button><button id="repair">Ремонт ${money(vehicles.repairCost(s))}</button></div><h3>Прокачка</h3><div class="actions">${Object.values(UpgradeType).map(t=>`<button data-upgrade="${t}">${t} · ${money(vehicles.upgradeCost(s,t))}</button>`).join('')}</div></section>`;
if(screen==='race'&&s)return `<section class="race"><p class="eyebrow">ГОНКА С БОТОМ</p><h2>${s.brand} ${s.model}</h2><div class="track"><div class="racecar you" style="--car:${s.color}"></div><div class="racecar bot"></div><i></i><i></i><i></i></div><p>Управление оптимизировано для мобильной игры. Результат учитывает характеристики и повреждения.</p><button class="primary" id="start-race">Старт гонки</button></section>`;
if(screen==='profile')return `<section class="panel"><p class="eyebrow">ПРОФИЛЬ</p><h2>Гонщик · уровень ${player.level}</h2><div class="xp"><i style="width:${Math.min(100,player.experience/xp.requiredForLevel(player.level)*100)}%"></i></div><p>${player.experience} / ${xp.requiredForLevel(player.level)} XP</p><h3>${money(player.balance)}</h3><p class="hint">Экономические операции проходят только через EconomyService.</p></section>`; return '';}
function render(){app.innerHTML=`<main><div class="top"><strong>◈ SPEED HAVEN</strong><button data-nav="profile">${money(player.balance)}</button></div>${message?`<div class="toast">${message}</div>`:''}${view()}</main>${nav()}`; bind();}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{screen=b.dataset.nav;message='';render();});document.querySelectorAll('[data-car]').forEach(b=>b.onclick=()=>{selectedId=b.dataset.car;screen='detail';render();});const input=document.querySelector('#photo-input');document.querySelector('#capture')?.addEventListener('click',()=>input.click());input?.addEventListener('change',e=>{const f=e.target.files[0];if(f){const r=new FileReader();r.onload=()=>{photo=r.result;render();};r.readAsDataURL(f);}});document.querySelector('#recognize')?.addEventListener('click',async()=>{const secured=await privacy.sanitize(photo);photo=secured.photo;recognized=await recognition.recognize(photo);screen='result';render();});document.querySelector('#confirm')?.addEventListener('click',()=>action(()=>{const rarity=rarityService(recognized);const vehicle=createVehicle({...recognized,rarity,photo});let p={...player,vehicles:[...player.vehicles,vehicle]};p=economy.credit(p,Math.round(vehicle.baseValue*.03),'discovery');screen='collection'; return xp.grant(p,90+['COMMON','UNCOMMON','RARE','EPIC','LEGENDARY'].indexOf(rarity)*30,'discovery');}));document.querySelector('#slot')?.addEventListener('click',()=>action(()=>garage.buySlot(player,economy)));document.querySelectorAll('[data-sell]').forEach(b=>b.onclick=()=>action(()=>market.sell(player,b.dataset.sell,economy)));const s=selected();document.querySelector('#park')?.addEventListener('click',()=>action(()=>s.garageSlot===null?garage.park(player,s.id):garage.unpark(player,s.id)));document.querySelector('#repair')?.addEventListener('click',()=>action(()=>vehicles.repair(player,s.id,economy)));document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>action(()=>vehicles.upgrade(player,s.id,b.dataset.upgrade,economy)));document.querySelector('#race')?.addEventListener('click',()=>{screen='race';render();});document.querySelector('#start-race')?.addEventListener('click',()=>action(()=>{const result=race.simulate(s,{speed:115,handling:65,damage:0},{accelerate:1,steer:.2});let p={...player,vehicles:player.vehicles.map(v=>v.id===s.id?vehicles.applyCollision(v,result.damage):v)};p=economy.credit(p,result.reward,result.won?'race_win':'race_finish');return xp.grant(p,result.won?80:25,'race');}));}
function rarityService(candidate){return rarity.calculate(candidate);} render();
